[package]
name = "sh4der-jockey"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[profile.release]
lto = true
#codegen-units = 1
panic = "abort"

[dependencies]
getopts = "0.2.21"
gl = "0.14.0"
imgui = { git = "https://github.com/luke-titley/imgui-docking-rs", branch = "release/docking/0.5.0" }
imgui-winit-support = { git = "https://github.com/luke-titley/imgui-docking-rs", branch = "release/docking/0.5.0",  default-features = false, features = ["winit-19"] }
imgui-opengl-renderer = { git = "https://github.com/sp4ghet/rust-imgui-opengl-renderer", branch = "master" }
glutin = "0.21.0"
lazy_static = "1.4.0"
regex = "1.4.6"
notify = "5.0.0-pre.7"
serde_yaml = "0.8.17"
midir = "0.7.0"
cpal = "0.13.3"
as-any = "0.2.0"
rand = "0.8.3"
num-complex = "0.4"
rustfft = "6.0"
image = "0.23"

[build-dependencies]
anyhow = "1.0.40"
vergen = "5.1.2"
