[package]
name = "sh4der-jockey"
version = "0.1.2"
edition = "2018"
build = "build.rs"

#[profile.release]
#lto = true
#codegen-units = 1
#panic = "abort"

[dependencies]
as-any = "0.2.0"
async-std = { version = "1.9.0", default-features = false, features = ["std"] }
cpal = "0.13.3"
futures = { version = "0.3.15", default-features = false }
getopts = "0.2.21"
gl = "0.14.0"
glutin = "0.26"
image = "0.23"
imgui = { git = "https://github.com/sp4ghet/imgui-rs", branch = "master" }
imgui-winit-support = { git = "https://github.com/sp4ghet/imgui-rs", branch = "master" }
imgui-opengl-renderer = { git = "https://github.com/sp4ghet/rust-imgui-opengl-renderer", branch = "master" }
lazy_static = "1.4.0"
midir = "0.7.0"
notify = "5.0.0-pre.7"
num-complex = "0.4"
rand = "0.8.3"
regex = "1.4.6"
rustfft = "6.0"
serde_yaml = "0.8.17"
take_mut = "0.2.2"
ndi =  "0.1.0"

[build-dependencies]
anyhow = "1.0.40"
vergen = { version = "5.1.2", default-features = false, features = ["build", "git"] }
