name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install libasound2-dev
        sudo apt-get install libgtk-3-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

# test_windows:
#   runs-on: windows-latest
#   steps:
#   - uses: actions/checkout@v2
#   - name: Build
#     run: cargo build --verbose
#   - name: Run tests
#     run: cargo test --verbose
